# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100 # Hz

    arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

arm_controller:
  ros__parameters:
    joints:
      - joint2
      - joint5
    command_interfaces:
      - position
    state_interfaces:
      - position
    # gains:
    #   joint1: {p: 1.0, i: 0.0, d: 0.1}
    #   joint2: {p: 1.0, i: 0.0, d: 0.1}
    #   joint3: {p: 1.0, i: 0.0, d: 0.1}
    #   joint4: {p: 1.0, i: 0.0, d: 0.1}
    #   joint5: {p: 1.0, i: 0.0, d: 0.1}
    #   joint6: {p: 1.0, i: 0.0, d: 0.1}

joint_state_broadcaster:
  ros__parameters: {}
